services:

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://host.docker.internal:1433;databaseName=restaurant_auth;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://host.docker.internal:1433;databaseName=restaurant_db;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

  reservation-service:
    build: ./reservation-service
    container_name: reservation-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://host.docker.internal:1433;databaseName=restaurant_reservation;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8084:8084"
    depends_on:
      - discovery-service
      - restaurant-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://host.docker.internal:1433;databaseName=restaurant_payment;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
      - auth-service
      - restaurant-service
      - reservation-service
      - payment-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

networks:
  default:
    name: quanlynhahang-network

