name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and test API Gateway
        run: mvn -B -f api-gateway/pom.xml clean verify -Dtest='!**/*ApplicationTests' -Dsurefire.failIfNoSpecifiedTests=false

      - name: Build and test Auth Service
        run: mvn -B -f auth-service/pom.xml clean verify -Dtest='!**/*ApplicationTests' -Dsurefire.failIfNoSpecifiedTests=false

      - name: Build and test Discovery Service
        run: mvn -B -f discovery-service/pom.xml clean verify -Dtest='!**/*ApplicationTests' -Dsurefire.failIfNoSpecifiedTests=false

      - name: Build and test Payment Service
        run: mvn -B -f payment-service/pom.xml clean verify -Dtest='!**/*ApplicationTests' -Dsurefire.failIfNoSpecifiedTests=false

      - name: Build and test Reservation Service
        run: mvn -B -f reservation-service/pom.xml clean verify -Dtest='!**/*ApplicationTests' -Dsurefire.failIfNoSpecifiedTests=false

      - name: Build and test Restaurant Service
        run: mvn -B -f restaurant-service/pom.xml clean verify -Dtest='!**/*ApplicationTests' -Dsurefire.failIfNoSpecifiedTests=false